name: ERRV Team Mobo
favicon: null
layout_spectrum: 0.74775
typography_spectrum: 0.7515
title: ERRV Team Mobo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f47af'
    - '#fcdd09'
    - '#607a75'
    - '#8c9655'
    - '#b9b237'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
