name: ERRV Team Mobo
favicon: null
layout_spectrum: 0.5153769257012755
typography_spectrum: 0.19521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f47af'
    - '#fcdd09'
    - '#607a75'
    - '#8c9655'
    - '#b9b237'
  brandStrength: 0.5
  lightness: 0.254665972199291
  saturation: 0.41477321297861636
  rhythmicContrast: 0.06096073403023183
purpose: []
